language: php
dist: trusty
matrix:
  include:
    - php: 5.4
      dist: precise
      env: PHP_VERSION="5.4"
    - php: 5.5
      env: PHP_VERSION="5.5"
    - php: 5.6
      env: PHP_VERSION="5.6"
    - php: 7.0
      env: PHP_VERSION="7.0"
    - php: 7.1
      env: PHP_VERSION="7.1"
    - php: 7.2
      env: PHP_VERSION="7.2"
    - php: 7.3
      env: PHP_VERSION="7.3"

addons:
  code_climate:
    repo_token: 89381e22acbd73c8e57e329eaadc7ee022d611897ede8d0c0032500f237cf28a

before_script:
  - travis_retry composer install

script:
  - mkdir -p build/logs
  - if [ `echo "$PHP_VERSION < 7.3" | bc` == 1 ]; then vendor/bin/phpunit --coverage-clover build/logs/coverage-clover.xml; fi
  - if [ `echo "$PHP_VERSION >= 7.3" | bc` == 1 ]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/coverage-clover.xml; fi

after_success:
  - vendor/bin/test-reporter --coverage-report build/logs/coverage-clover.xml
  - vendor/bin/coveralls -v