language: php
dist: trusty
matrix:
  include:
    - php: 7.2
      env: PHP_VERSION="7.2"
    - php: 7.3
      env: PHP_VERSION="7.3"

before_script:
  - travis_retry composer install

script:
  - mkdir -p build/logs
  - if [ `echo "$PHP_VERSION < 7.3" | bc` == 1 ]; then vendor/bin/phpunit --coverage-clover build/logs/coverage-clover.xml; fi
  - if [ `echo "$PHP_VERSION >= 7.3" | bc` == 1 ]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/coverage-clover.xml; fi

